### ISSUE TITLE
Missing contrast on code block and additional task description

### ISSUE THREAD

**Issue by Citvej** [Bbioon/codeable-darkmode-css#4]
I noticed two issues with text not being visible:
1. When using `code block` using backticks \`
2. In the project scope tool's textarea.

Class names:
1. Code block is plain html \<code\> tag. I don't think there's a difference between inline and multi-line code in Codeable as it always prints it out as multi-line.
2. For the scope item description (textarea), the structure is as follows: div.scope-doc-item__bottom > div.scope-doc-item__bottom__description. I think it's enough. Currently the color is set as:
``` CSS
cdbl-project-scope-doc-view .scope-doc-item .scope-doc-item__bottom__description {
position: relative;
font-family: URWGeometric;
font-size: 16px;
font-weight: 500;
font-style: oblique;
line-height: 1.5;
letter-spacing: .3px;
color: #151d22;
}
```
_note: cdbl-project-scope-doc-view is a custom HTML component, not a class or id name_
